# Default values for book-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bookNameSpace: "book-ns"

auth:
  tokens: "NThjZWYxMzYtYWNkYi00OWZiLWI0OGUtYTVmMDIwYzNjYWJiLDFhMjUxN2ZlLTVhMGQtNDNhNS1hZGI0LTIyN2UzOWQwMmY3OA=="

authors:
  image: "bff-authors-service:1.0"
  replicaCount: 1
  port: 8080

books:
  image: "bff-books-service:1.0"
  replicaCount: 1
  port: 8080

frontend:
  image: "bff-frontend:1.0"
  replicaCount: 1
  port: 1805

webSockets:
  image: "bff-web-sockets-service:1.0"
  replicaCount: 1
  port: 8080

briefAggregator:
  image: "bff-brief-aggregator:1.0"
  replicaCount: 1
  port: 2105

gateway:
  image: "bff-gateway:1.0"
  replicaCount: 1
  port: 8080

briefGateway:
  image: "bff-gateway:1.0"
  replicaCount: 1
  port: 8080

redis:
  host: "redis-service-master.data-ns.svc.cluster.local"
  port: "6379"
  password: ""
  timeout: "60000"
  database: "0"
  channel:
    authors: "authors"
    books: "books"
