apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bff-authors
  name: bff-authors
  namespace: {{ .Values.bookNameSpace }}
spec:
  replicas: {{ .Values.authors.replicaCount }}
  selector:
    matchLabels:
      app: bff-authors
  template:
    metadata:
      labels:
        app: bff-authors
    spec:
      containers:
        - name: bff-authors
          image: {{ .Values.authors.image }}
          imagePullPolicy: Never

          env:
            - name: SERVER_PORT
              value: "{{ .Values.authors.port }}"

            - name: REDIS_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: channels-configmap
                  key: REDIS_AUTHORS_CHANNEL

            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD

          envFrom:
            - configMapRef:
                name: redis-configmap

          ports:
            - containerPort: {{ .Values.authors.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: bff-authors-service
  namespace: {{ .Values.bookNameSpace }}
spec:
  type: ClusterIP
  selector:
    app: bff-authors
  ports:
    - port: {{ .Values.authors.port }}
      targetPort: {{ .Values.authors.port }}
