apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: brief-gateway
  name: brief-gateway
  namespace: {{ .Values.bookNameSpace }}
spec:
  replicas: {{ .Values.briefGateway.replicaCount }}
  selector:
    matchLabels:
      app: brief-gateway
  template:
    metadata:
      labels:
        app: brief-gateway
    spec:
      containers:
        - name: brief-gateway
          image: {{ .Values.briefGateway.image }}
          imagePullPolicy: Never

          env:
            - name: SERVER_PORT
              value: "{{ .Values.briefGateway.port }}"

            - name: AUTH_TOKENS
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: AUTH_TOKENS

            - name: REDIS_LIMIT_REPLENISHRATE
              value: "1"
            - name: REDIS_LIMIT_BURSTCAPACITY
              value: "2"

            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD

          envFrom:
            - configMapRef:
                name: redis-configmap
            - configMapRef:
                name: brief-services-configmap

          ports:
            - containerPort: {{ .Values.briefGateway.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: brief-gateway-service
  namespace: {{ .Values.bookNameSpace }}
spec:
  type: NodePort
  selector:
    app: brief-gateway
  ports:
    - name: http
      port: {{ .Values.briefGateway.port }}
      targetPort: {{ .Values.briefGateway.port }}
