apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: brief-gateway
  name: brief-gateway
  namespace: book-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brief-gateway
  template:
    metadata:
      labels:
        app: brief-gateway
    spec:
      containers:
        - name: brief-gateway
          image: bff-gateway:1.0
          imagePullPolicy: Never

          env:
            - name: AUTH_TOKENS
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: AUTH_TOKENS

            - name: REDIS_LIMIT_REPLENISHRATE
              value: "1"
            - name: REDIS_LIMIT_BURSTCAPACITY
              value: "2"

            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD

          envFrom:
            - configMapRef:
                name: redis-configmap
            - configMapRef:
                name: brief-services-configmap

          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: brief-gateway-service
  namespace: book-ns
spec:
  type: NodePort
  selector:
    app: brief-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
