apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bff-gateway
  name: bff-gateway
  namespace: book-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-gateway
  template:
    metadata:
      labels:
        app: bff-gateway
    spec:
      containers:
        - name: bff-gateway
          image: bff-gateway:1.0
          imagePullPolicy: Never

          env:
            - name: AUTH_TOKENS
              value: "58cef136-acdb-49fb-b48e-a5f020c3cabb,1a2517fe-5a0d-43a5-adb4-227e39d02f78"

            - name: AUTHORS_URL
              value: "http://bff-authors-service.book-ns.svc.cluster.local:8080"
            - name: BOOKS_URL
              value: "http://bff-books-service.book-ns.svc.cluster.local:8080"
            - name: BOOKDETAILS_URL
              value: "http://bff-frontend-service.book-ns.svc.cluster.local:1805"

            - name: WEBSOCKET_URL
              value: "ws://bff-web-sockets-service.book-ns.svc.cluster.local:8080"
            - name: WEBSOCKET_SOCKJS_URL
              value: "http://bff-web-sockets-service.book-ns.svc.cluster.local:8080"
            - name: WEBSOCKET_PATH
              value: "/push"

            - name: REDIS_LIMIT_REPLENISHRATE
              value: "1"
            - name: REDIS_LIMIT_BURSTCAPACITY
              value: "2"

          envFrom:
            - configMapRef:
                name: redis-configmap

          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bff-gateway-service
  namespace: book-ns
spec:
  type: NodePort
  selector:
    app: bff-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
