apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress
  namespace: book-ns
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  backend:
    serviceName: bff-gateway-service
    servicePort: 8080

  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: bff-gateway-service
              servicePort: 8080

    - host: book.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: bff-gateway-service
              servicePort: 8080

    - host: brief.book.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: brief-gateway-service
              servicePort: 8080
