apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-0
  namespace: data-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  resources:
    requests:
      storage: 1Gi
